version: 2
jobs:
  deployDev:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Dev to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME_DEV.git dev:master
  deployProd:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Prod to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME_PROD.git master:master

workflows:
  version: 2
  build-deploy:
    jobs:
      - deployDev:
          filters:
            branches:
              only: dev
      - deployProd:
          filters:
            branches:
              only: master